webtalk_init -webtalk_dir E:/CN2/Lucrare3/Lucrare3/IF_ID_Vivado_Without_Control/IF_ID/IF_ID.sim/sim_1/behav/xsim/xsim.dir/vreau_afara_la_zapada_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jan 14 15:21:13 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8a9e6479-a480-45a3-b8d4-7a30fa995b13" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bb560ed3935d47718a06097adf9806b4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "82" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2494 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6824_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2019731409 -regid "" -xml E:/CN2/Lucrare3/Lucrare3/IF_ID_Vivado_Without_Control/IF_ID/IF_ID.sim/sim_1/behav/xsim/xsim.dir/vreau_afara_la_zapada_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/CN2/Lucrare3/Lucrare3/IF_ID_Vivado_Without_Control/IF_ID/IF_ID.sim/sim_1/behav/xsim/xsim.dir/vreau_afara_la_zapada_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/CN2/Lucrare3/Lucrare3/IF_ID_Vivado_Without_Control/IF_ID/IF_ID.sim/sim_1/behav/xsim/xsim.dir/vreau_afara_la_zapada_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
