@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Jan 14 13:37:02 +0200 2021
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim vreau_afara_la_zapada_behav -key {Behavioral:sim_1:Functional:vreau_afara_la_zapada} -tclbatch vreau_afara_la_zapada.tcl -log simulate.log"
call xsim  vreau_afara_la_zapada_behav -key {Behavioral:sim_1:Functional:vreau_afara_la_zapada} -tclbatch vreau_afara_la_zapada.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
